#!/usr/bin/env bun
/**
 * Sigma Install Script
 *
 * Playwright용 스크립트를 빌드하고, 결과물 경로를 서버 .env에 기록합니다.
 *
 * 사용법:
 *   bun run install                          # 기본 (packages/shared/dist/)
 *   bun run install -- --dir ~/.sigma/scripts  # 경로 지정 (빌드 후 복사)
 *
 * 동작:
 *   1. packages/shared/ 빌드 (extractor.standalone.js 생성)
 *   2. --dir 지정 시 빌드 결과를 해당 경로로 복사
 *   3. packages/server/.env에 SIGMA_SCRIPTS_DIR 기록
 */

import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { existsSync, mkdirSync, copyFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SHARED_DIR = resolve(ROOT, 'packages/shared');
const SERVER_DIR = resolve(ROOT, 'packages/server');
const BUILD_OUTPUT = resolve(SHARED_DIR, 'dist/extractor.standalone.js');

function parseArgs(): { dir?: string } {
  const args = process.argv.slice(2);
  const dirIdx = args.indexOf('--dir');
  if (dirIdx !== -1 && args[dirIdx + 1]) {
    return { dir: resolve(args[dirIdx + 1]) };
  }
  return {};
}

async function main() {
  const { dir: targetDir } = parseArgs();

  console.log('=== Sigma Install ===\n');

  // Step 1: Build shared package
  console.log('[1/3] Building shared extractor...');
  try {
    execSync('bun run build', { cwd: SHARED_DIR, stdio: 'inherit' });
  } catch {
    console.error('Build failed. Run `bun install` first if dependencies are missing.');
    process.exit(1);
  }

  if (!existsSync(BUILD_OUTPUT)) {
    console.error(`Build output not found: ${BUILD_OUTPUT}`);
    process.exit(1);
  }

  // Step 2: Copy to target dir if specified
  let scriptsDir = resolve(SHARED_DIR, 'dist');

  if (targetDir) {
    console.log(`[2/3] Copying to ${targetDir}...`);
    mkdirSync(targetDir, { recursive: true });
    const dest = resolve(targetDir, 'extractor.standalone.js');
    copyFileSync(BUILD_OUTPUT, dest);
    scriptsDir = targetDir;
    console.log(`  Copied: ${dest}`);
  } else {
    console.log('[2/3] Using build output directly (no --dir specified)');
  }

  // Step 3: Write server .env
  console.log('[3/3] Writing server .env...');
  const envPath = resolve(SERVER_DIR, '.env');
  const envContent = `# Auto-generated by scripts/install.ts\nSIGMA_SCRIPTS_DIR=${scriptsDir}\n`;
  writeFileSync(envPath, envContent);
  console.log(`  Written: ${envPath}`);
  console.log(`  SIGMA_SCRIPTS_DIR=${scriptsDir}`);

  console.log('\n=== Install complete ===');
  console.log('Start the server with: bun run start');
}

main().catch((err) => {
  console.error('Install failed:', err);
  process.exit(1);
});
