// 서버(WebSocket) → UI 메시지 타입 상수
export const SERVER_MSG = {
  REGISTERED: 'REGISTERED',
  CREATE_FRAME: 'CREATE_FRAME',
  GET_FRAMES: 'GET_FRAMES',
  GET_PAGES: 'GET_PAGES',
  DELETE_FRAME: 'DELETE_FRAME',
  UPDATE_FRAME: 'UPDATE_FRAME',
  MODIFY_NODE: 'MODIFY_NODE',
  FIND_NODE: 'FIND_NODE',
  GET_TREE: 'GET_TREE',
  CREATE_SECTION: 'CREATE_SECTION',
  MOVE_NODE: 'MOVE_NODE',
  EXPORT_IMAGE: 'EXPORT_IMAGE',
  EXTRACT_NODE_JSON: 'EXTRACT_NODE_JSON',
  EXTRACT_JSON: 'EXTRACT_JSON',
  EXTRACT_HTML: 'EXTRACT_HTML',
  TEST_ROUNDTRIP_JSON: 'TEST_ROUNDTRIP_JSON',
  TEST_ROUNDTRIP_HTML: 'TEST_ROUNDTRIP_HTML',
  PING: 'PING',
  IMPORTED: 'IMPORTED',
  CHUNK_START: 'CHUNK_START',
  CHUNK: 'CHUNK',
  CHUNK_END: 'CHUNK_END',
  CLONE_NODE: 'CLONE_NODE',
} as const;

// 플러그인(code.ts) → UI 메시지 타입 상수
export const PLUGIN_MSG = {
  SUCCESS: 'success',
  ERROR: 'error',
  INFO: 'info',
  FILE_INFO: 'file-info',
  FRAMES_LIST: 'frames-list',
  PAGES_LIST: 'pages-list',
  DELETE_RESULT: 'delete-result',
  UPDATE_RESULT: 'update-result',
  MODIFY_RESULT: 'modify-result',
  EXTRACT_RESULT: 'extract-result',
  ROUNDTRIP_RESULT: 'roundtrip-result',
  FIND_NODE_RESULT: 'find-node-result',
  TREE_RESULT: 'tree-result',
  EXPORT_IMAGE_RESULT: 'export-image-result',
  EXTRACT_NODE_JSON_RESULT: 'extract-node-json-result',
  CREATE_SECTION_RESULT: 'create-section-result',
  MOVE_NODE_RESULT: 'move-node-result',
  CLONE_NODE_RESULT: 'clone-node-result',
} as const;
